#!/usr/bin/env bash

kubectl config set-credentials fakeuser \
   --auth-provider=oidc \
   --auth-provider-arg=idp-issuer-url=https://uaa.uaa-acceptance.cf-app.com/ \
   --auth-provider-arg=client-id=birdkubeclient \
   --auth-provider-arg=client-secret=birdkubeclientsecret \
   --auth-provider-arg=idp-certificate-authority=/Users/pivotal/.minikube/certs/oidc.pem \
   --auth-provider-arg=id-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjJiYjY5ZS0zOGI5LTRiY2MtODQ0Yy1lNTBiZmRiOThjYzAiLCJhdWQiOlsiYmlyZGt1YmVjbGllbnQiXSwiaXNzIjoiaHR0cHM6Ly91YWEudWFhLWFjY2VwdGFuY2UuY2YtYXBwLmNvbS9vYXV0aC90b2tlbiIsImV4cCI6MTU3MTkwMTU1MiwiaWF0IjoxNTcxODU4MzUyLCJhbXIiOlsicHdkIl0sImF6cCI6ImJpcmRrdWJlY2xpZW50Iiwic2NvcGUiOlsib3BlbmlkIiwiZm9vYmFyIl0sImZha2Vfcm9sZXMiOlsiZmFrZV9yb2xlMSJdLCJlbWFpbCI6ImF3aXR0cm9ja0BwaXZvdGFsLmlvIiwiemlkIjoidWFhIiwib3JpZ2luIjoidWFhIiwianRpIjoiODJlMzBlMDA3NWM0NDBiNGFiMDYzZjI2ZjMyZWY5NDIiLCJwcmV2aW91c19sb2dvbl90aW1lIjoxNTcxODU4MjU0MTAyLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY2xpZW50X2lkIjoiYmlyZGt1YmVjbGllbnQiLCJjaWQiOiJiaXJka3ViZWNsaWVudCIsImdyYW50X3R5cGUiOiJwYXNzd29yZCIsInVzZXJfbmFtZSI6ImJpcmRrdWJlIiwicmV2X3NpZyI6ImNiNzQ3YmFjIiwidXNlcl9pZCI6IjJiMmJiNjllLTM4YjktNGJjYy04NDRjLWU1MGJmZGI5OGNjMCIsImF1dGhfdGltZSI6MTU3MTg1ODM1Mn0.f1nNcwUhCNWbiqTJRiKELSrDXaKSnInTq5g4SdBLHQY